In [2]:
import pickle

import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression

In [8]:
df = pd.read_csv('data/modeling_data/no_sw_mtf.csv')

In [26]:
df.columns

Index(['yr_adminst', 'region', 'msa', 'smsa', 'evr_smoked_cig',
       'cig_month_freq', 'alcohol_lifetime_freq', 'alcohol_yr_freq',
       'alcohol_2weeks', 'sex', 'area_type', 'marital_status', 'has_father',
       'has_mother', 'has_siblings', 'father_educ_lvl', 'mother_educ_lvl',
       'mother_employed', 'political_value_type', 'relig_attd',
       'relig_importance', 'academic_self_rating', 'intelligence_self_rating',
       'school_missed_illness', 'school_missed_ditched', 'school_missed_other',
       'skipped_class', 'avg_grade', 'tech_school_after_hs',
       'military_after_hs', '2yrcoll_after_hs', '4yrcoll_after_hs',
       'gradsch_after_hs', 'desire_tech_school', 'desire_military',
       'desire_2yrcoll', 'desire_4yrcoll', 'desire_gradsch', 'desire_none',
       'work_hrs', 'work_pay', 'other_income', 'rec_time', 'date_freq',
       'drive_freq', '12mo_r_tcktd', '12mo_accidents', 'binary_drug'],
      dtype='object')

In [14]:
for col in df.columns:
    print(df[col].value_counts(), '\n\n')

1995    8776
1996    8077
1997    7187
2007    6986
1998    6965
2006    6961
2003    6934
2005    6796
2004    6745
2010    6318
2002    6190
2008    6188
2009    6096
2011    6085
2012    5738
2019    4531
2015    4461
2014    4414
1999    4154
2001    3789
2000    3644
Name: yr_adminst, dtype: int64


South        51586
Midwest      41042
NorthEast    31374
West          3033
Name: region, dtype: int64


0    86344
1    40691
Name: msa, dtype: int64


1    98995
0    28040
Name: smsa, dtype: int64


Never                64010
1-2x                 25249
Occasionally         16650
Regularly Now        14235
Regularly in Past     6891
Name: evr_smoked_cig, dtype: int64


None              96914
<1 Cigarettes     12400
1-5 Cigarettes     8856
2 Packs            5067
1 Pack             2995
1.5 Packs           578
2+ Packs            225
Name: cig_month_freq, dtype: int64


0         30756
40+       27832
10-19X    16308
20-39X    14748
3-5X      14194
6-9X      12665
1-2X      10532
Name: alcohol_lifetime_freq, dtype: int64


0         38375
1-2X      21161
3-5X      17450
10-19X    15437
6-9X      13673
40+       11030
20-39X     9909
Name: alcohol_yr_freq, dtype: int64


None     92738
Once     12744
Twice     9271
3-5X      8610
6-9X      2308
10+X      1364
Name: alcohol_2weeks, dtype: int64


Female    67583
Male      59452
Name: sex, dtype: int64


Small Town                   37664
Medium City                  16997
Country                      15508
Suburb of Medium City        13814
Large City                   11707
Suburb of Large City         11648
Suburb of Vry Lrg City        7172
City >500,000 (Vry Large)     7140
Farm                          5385
Name: area_type, dtype: int64


Single                117537
Engaged                 5483
Married                 2956
Separated/Divorced      1059
Name: marital_status, dtype: int64


Yes    99412
No     27623
Name: has_father, dtype: int64


Yes    116688
No      10347
Name: has_mother, dtype: int64


Yes    87470
No     39565
Name: has_siblings, dtype: int64


Graduated HS        36514
College Grad        32282
Some College        22677
Graduate School     20284
Some High School    11681
Grade School         3597
Name: father_educ_lvl, dtype: int64


College Grad        37038
Graduated HS        34816
Some College        26262
Graduate School     17919
Some High School     8255
Grade School         2745
Name: mother_educ_lvl, dtype: int64


Yes/Nearly All    61783
Yes/Some          25367
Yes/Most          21778
No                18107
Name: mother_employed, dtype: int64


Don't Know           38434
Moderate             35040
Liberal              20823
Conservative         17904
Very Liberal          6534
Very Conservative     5664
Radical               2636
Name: political_value_type, dtype: int64


Rarely         42881
Every Week+    41670
1-2x Month     21259
Never          21225
Name: relig_attd, dtype: int64


Very Important        36491
Pretty Important      35777
A Little Important    31972
Not Important         22795
Name: relig_importance, dtype: int64


Above Average             42183
Average                   35858
Slightly Above Average    31814
Far Above Average         10655
Slightly Below Avg         4334
Below Avg                  1562
Far Below                   629
Name: academic_self_rating, dtype: int64


Above Average             42039
Average                   34140
Slightly Above Average    32960
Far Above Average         12175
Slightly Below Avg         3906
Below Avg                  1277
Far Below                   538
Name: intelligence_self_rating, dtype: int64


0       77371
1       22771
2       12729
3        6805
4-5      4754
6-10     1791
11+       814
Name: school_missed_illness, dtype: int64


0       90812
1       17380
2        8103
3        4709
4-5      3512
6-10     1493
11+      1026
Name: school_missed_ditched, dtype: int64


0       72341
1       26364
2       13760
3        6932
4-5      4907
6-10     1839
11+       892
Name: school_missed_other, dtype: int64


0        89428
1-2      22706
3-5       9254
6-10      3330
11-20     1309
21+       1008
Name: skipped_class, dtype: int64


A+    25771
A-    24407
B+    24114
B     22052
B-    13172
C+     9159
C      5359
C-     2167
D       834
Name: avg_grade, dtype: int64


Definitely Won't    78885
Probably Won't      27032
Probably Will       12900
Definitely Will      8218
Name: tech_school_after_hs, dtype: int64


Definitely Won't    93084
Probably Won't      22600
Probably Will        6507
Definitely Will      4844
Name: military_after_hs, dtype: int64


Definitely Won't    60019
Probably Won't      25334
Probably Will       21857
Definitely Will     19825
Name: 2yrcoll_after_hs, dtype: int64


Definitely Will     83198
Probably Will       24852
Probably Won't      10155
Definitely Won't     8830
Name: 4yrcoll_after_hs, dtype: int64


Probably Will       44532
Probably Won't      33167
Definitely Will     30273
Definitely Won't    19063
Name: gradsch_after_hs, dtype: int64


No     109758
Yes     17277
Name: desire_tech_school, dtype: int64


No     111242
Yes     15793
Name: desire_military, dtype: int64


No     99990
Yes    27045
Name: desire_2yrcoll, dtype: int64


Yes    106490
No      20545
Name: desire_4yrcoll, dtype: int64


Yes    78775
No     48260
Name: desire_gradsch, dtype: int64


No     121996
Yes      5039
Name: desire_none, dtype: int64


0            35539
16-20        18676
11-15        15075
21-25        14211
6-10         13336
5 or less    12567
26-30         9134
30+           8497
Name: work_hrs, dtype: int64


0          41717
76-125     26155
126-175    20283
51-75      13192
36-50       8083
21-35       5529
176+        3914
11-20       3741
6-10        3245
1-5         1176
Name: work_pay, dtype: int64


0          50932
11-20      22807
21-35      14090
6-10       13035
36-50       8268
1-5         7481
51-75       3841
76-125      2933
126-175     2753
176+         895
Name: other_income, dtype: int64


2      35689
3      31349
4-5    20829
1      18068
<1     12039
6-7     9061
Name: rec_time, dtype: int64


Never         32776
1x Month      22913
2-3x Week     21410
2-3x Month    19834
1x Week       18948
3x Week+      11154
Name: date_freq, dtype: int64


11-50      32199
51-100     30257
101-200    22355
0          17922
200+       14414
1-10        9888
Name: drive_freq, dtype: int64


0     91488
1     22489
2      7846
3      3106
4+     2106
Name: 12mo_r_tcktd, dtype: int64


0     97301
1     23068
2      5108
3      1152
4+      406
Name: 12mo_accidents, dtype: int64


0    78999
1    48036
Name: binary_drug, dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127035 entries, 0 to 127034
Data columns (total 48 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   yr_adminst                127035 non-null  int64
 1   region                    127035 non-null  object
 2   msa                       127035 non-null  int64
 3   smsa                      127035 non-null  int64
 4   evr_smoked_cig            127035 non-null  object
 5   cig_month_freq            127035 non-null  object
 6   alcohol_lifetime_freq     127035 non-null  object
 7   alcohol_yr_freq           127035 non-null  object
 8   alcohol_2weeks            127035 non-null  object
 9   sex                       127035 non-null  object
 10  area_type                 127035 non-null  object
 11  marital_status            127035 non-null  object
 12  has_father                127035 non-null  object
 13  has_mother                127035 non-null  object
 14  has_siblings              127035 non-null  object
 15  father_educ_lvl           127035 non-null  object
 16  mother_educ_lvl           127035 non-null  object
 17  mother_employed           127035 non-null  object
 18  political_value_type      127035 non-null  object
 19  relig_attd                127035 non-null  object
 20  relig_importance          127035 non-null  object
 21  academic_self_rating      127035 non-null  object
 22  intelligence_self_rating  127035 non-null  object
 23  school_missed_illness     127035 non-null  object
 24  school_missed_ditched     127035 non-null  object
 25  school_missed_other       127035 non-null  object
 26  skipped_class             127035 non-null  object
 27  avg_grade                 127035 non-null  object
 28  tech_school_after_hs      127035 non-null  object
 29  military_after_hs         127035 non-null  object
 30  2yrcoll_after_hs          127035 non-null  object
 31  4yrcoll_after_hs          127035 non-null  object
 32  gradsch_after_hs          127035 non-null  object
 33  desire_tech_school        127035 non-null  object
 34  desire_military           127035 non-null  object
 35  desire_2yrcoll            127035 non-null  object
 36  desire_4yrcoll            127035 non-null  object
 37  desire_gradsch            127035 non-null  object
 38  desire_none               127035 non-null  object
 39  work_hrs                  127035 non-null  object
 40  work_pay                  127035 non-null  object
 41  other_income              127035 non-null  object
 42  rec_time                  127035 non-null  object
 43  date_freq                 127035 non-null  object
 44  drive_freq                127035 non-null  object
 45  12mo_r_tcktd              127035 non-null  object
 46  12mo_accidents            127035 non-null  object
 47  binary_drug               127035 non-null  int64
dtypes: int64(4), object(44)
memory usage: 46.5+ MB

In [16]:
X = df.drop(["binary_drug", "smsa"], axis=1)
y = df["binary_drug"]

In [19]:
# Note: we are not doing a train-test split, since we already have a "final"
# model chosen based on some previous train-test split. We want the best possible
# model, so we fit with the entire training set.

# Instantiate a pipeline that performs all preprocessing steps
pipe = Pipeline(steps=[
       ("ohe", OneHotEncoder(sparse=False, handle_unknown="ignore")),
       ("logistic_model", LogisticRegression(max_iter=10000, C=0.1))])

In [20]:
# Fit the pipeline on the full dataset
pipe.fit(X, y)

Pipeline(steps=[('ohe', OneHotEncoder(handle_unknown='ignore', sparse=False)),
                ('logistic_model', LogisticRegression(C=0.1, max_iter=10000))])

In [21]:
# Not needed, but print out the coefficients as a way to demonstrate that the
# model was successfully fitted
print("coefficients")
print(pipe.named_steps["logistic_model"].coef_)

# Save the fitted pipeline
with open("src/models/model.pkl", 'wb') as f:
    pickle.dump(pipe, f)

coefficients
[[-5.32244034e-01 -4.40360028e-01 -3.87914409e-01 -4.86894276e-01
  -4.40103072e-01 -4.01147876e-01 -2.18115751e-01 -1.54255002e-01
  -1.64660110e-01 -1.44238627e-01 -1.81662304e-02 -9.26911163e-02
  -9.88541061e-02 -5.00211355e-02  6.05503536e-02  2.24383662e-01
   3.99503193e-01  4.06440068e-01  6.90329160e-01  7.25483334e-01
   1.12594879e+00 -1.22516601e-01  5.15633538e-02 -4.69261883e-02
   1.20852221e-01  2.21197166e-02 -1.91469311e-02 -1.56055554e-01
  -9.93653371e-01  1.91954660e-01  6.11081114e-01  3.49645937e-01
   1.48650413e-01  3.02527389e-02  9.40603601e-02  4.37542565e-02
   2.07034897e-01 -1.01005086e-01 -4.19774795e-01 -5.09432483e-01
  -3.02252568e-01  1.64224847e-01  3.34104555e-01 -1.39973740e-01
   4.08531539e-01  4.77706355e-02 -1.06198996e+00 -4.66697957e-01
   3.34267973e-01  4.87084168e-01 -9.51064645e-02  6.59355601e-01
   1.46059422e-01 -8.16709748e-02  1.64601497e-01  1.20509580e-01
  -2.38751037e-01 -1.54084195e-02  5.36921404e-02 -4.07305737e-03
   7.04584291e-03  7.70246840e-02 -1.88345081e-01 -6.54062928e-01
   1.38780069e-01  2.00093846e-01  4.97308499e-02  1.14431039e-01
   1.88549778e-01  7.67705283e-02 -2.45505886e-02 -9.56917192e-02
   1.03143341e-01  2.00717521e-02  9.01060246e-02 -8.71332391e-02
   5.97867924e-02 -5.68140069e-02  1.57941957e-02 -1.28214102e-02
  -2.90101455e-03 -4.46646016e-02  3.31974327e-02  1.22314327e-04
   2.95924201e-04  1.69227305e-02  3.80318068e-02 -1.14341486e-01
   5.00076475e-02 -7.18035599e-02  2.99108856e-02  7.11674914e-02
  -3.17192730e-02  1.90289705e-02  2.00245304e-02 -4.36144239e-03
  -2.36369400e-01 -1.15256243e-01  1.08274387e-01 -8.35449248e-02
   3.65883925e-01 -3.72005972e-01  3.35991013e-01 -9.69176617e-03
  -1.58699147e-01  1.31004437e-01  4.03592620e-02  3.65907995e-02
   1.61733944e-01 -5.64612369e-02 -1.38890721e-01 -1.17477101e-02
  -2.01187670e-02  1.52971174e-02 -3.02026840e-02  1.80576858e-02
   2.17632348e-03  2.95108200e-02  1.02349803e-01 -7.63250729e-02
  -5.45135518e-02  2.48206179e-01 -1.33128381e-01  4.23936547e-02
  -1.26009845e-01 -1.34343347e-01 -3.72852928e-02 -3.87798260e-02
   8.91996719e-03  7.31414104e-02  4.92290193e-02  8.20908540e-02
  -2.64864477e-01 -1.10667185e-01  2.74013216e-01  2.46313978e-03
  -2.10322018e-03  8.82809237e-02  1.58503884e-02  5.64049297e-03
   3.93884456e-02 -3.03718318e-03  5.69785203e-02 -4.84607049e-02
   2.59274571e-02 -7.34642424e-02 -3.20225028e-01 -2.72047303e-02
  -1.42323172e-02  1.60118252e-01  9.27938006e-02  1.11722808e-01
  -4.51751276e-01 -2.74523803e-01 -9.02722606e-02 -1.65492461e-01
   4.87883023e-02  1.87685691e-01  1.16378820e-01  2.18339444e-01
   4.13820328e-01 -1.55781965e-02  3.81988171e-02 -2.44272781e-02
   4.77944300e-03 -2.17685225e-01  3.21801739e-02  1.19427360e-01
   6.90504761e-02 -3.48359890e-03 -1.50034832e-02  2.08088246e-02
   6.51043023e-04 -2.33416868e-02 -9.09746761e-02  7.84944201e-02
   3.87947284e-02 -6.45900455e-02  3.72304671e-02  2.09370140e-03
   2.82386626e-02  2.27150329e-02 -1.97422474e-02  1.80837566e-02
  -1.51109710e-02  1.44196692e-02 -1.14468837e-02 -3.80400701e-02
   4.10128557e-02 -3.40183586e-02  3.69911442e-02 -8.42907674e-02
   8.72635529e-02 -4.64241847e-02  1.73619561e-02  3.06933345e-02
   1.07608472e-01  4.44948247e-02 -3.85295931e-02 -3.84294250e-02
  -7.38025986e-02 -2.38621629e-02 -4.41767795e-02 -1.43928030e-02
   4.56392757e-03 -4.41399121e-02  2.54631433e-02 -5.38674297e-03
   1.40223924e-02  8.24702262e-02  8.41149657e-03 -9.58927371e-02
   3.19878704e-02 -1.91023192e-03  5.03872844e-02  1.07873629e-01
  -2.54236069e-02  1.81012590e-03  1.73803343e-02 -4.70220734e-02
  -3.62178086e-02 -1.46700466e-01 -7.44224116e-02  3.15684893e-02
   1.70735479e-01  1.85139934e-01 -1.63348239e-01  3.80463935e-02
   2.70250046e-02  7.74774666e-02 -1.75680221e-02 -4.61506160e-02
  -7.58574411e-02  5.91070113e-02  7.57350065e-02 -3.87646501e-02
   4.71199428e-02 -1.52838348e-01  1.26138229e-02 -1.75121490e-01
   1.50231672e-03  1.79026236e-02  1.21291714e-01  3.73976216e-02
  -2.57988042e-01 -1.40099550e-01  1.05681291e-03  2.02601788e-01
   1.97401777e-01]]

In [22]:
preds = pipe.predict(X)

In [23]:
from sklearn.metrics import accuracy_score, recall_score

In [24]:
accuracy_score(y, preds)

0.8019443460463652

In [25]:
recall_score(y, preds)

0.7076151219918394